"""doctors table

Revision ID: 14c3d6562cf3
Revises: 8e48fcbbfbed
Create Date: 2020-08-21 20:11:48.315045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c3d6562cf3'
down_revision = '8e48fcbbfbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('qual', sa.String(length=20), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_full_name'), 'doctor', ['full_name'], unique=False)
    op.add_column('patient', sa.Column('city', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'city')
    op.drop_index(op.f('ix_doctor_full_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
